# _config.yml
  
  

lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
url: "https://awelvor.github.io/asptt/"
title: "Asptt"
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge


  
